StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager manager, Cart cartService)
        {
            _manager = manager;
            _cart = cartService;
        }


        public ViewResult Checkout()=> View(new Order());
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order)
        {
            if (_cart.Lines.Count() == 0)
                ModelState.AddModelError("", "Sorry,your cart is empty");

            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new { OrderId = order.OrderId });
            }
            else
            {
                return View();
            }
        }
    }
}

StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _manager;
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
       

        public CartModel(IServiceManager manager,Cart cartService)
        {
            _manager = manager;
            Cart = cartService;
          
        }



        public void OnGet(string returnUrl)
        {
            ReturnUrl= returnUrl ?? "/";
           // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();

        }

        public IActionResult OnPost(int id,string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(id, false);

            if (product is not null)
            {
               // Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
                Cart.AddItem(product, 1);
              //  HttpContext.Session.SetJson<Cart>("cart",Cart);
            }

            return RedirectToPage(new {ReturnUrl=returnUrl});
        }

        public IActionResult OnPostRemove(int id , string returnUrl)
        {
          //  Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.Id == id).Product);
            //HttpContext.Session.SetJson<Cart>("cart", Cart);
            return Page();
        }
    }
}

StoreApp/Pages/Complete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

StoreApp/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class DemoModel : PageModel
    {
      

        public String? FullName =>  HttpContext?.Session?.GetString("name")??"";
        public void OnGet()
        {
        }

        public void OnPost([FromForm]string name) 
        {
            // FullName= name;

            HttpContext.Session.SetString("name", name);

        }    
    }
}

StoreApp/Pages/Cart.cshtml
@page "/cart"



@model CartModel


<div>
    <div class="text-center display-6">
        Cart
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>SubTotal</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <td>@line.Product.ProductName</td>
                    <td>@line.Quantity</td>
                    <td>@line.Product.Price.ToString("c")</td>
                    <td>@((line.Product.Price * line.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.Id" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>Remove
                            </button>
                        </form>
                    </td>
                </tr>

            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-right">Total : </td>
                <td class="text-right text-danger">@Model.Cart?.ComputeTotalValue().ToString("C2") </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
        <a class="btn btn-primary mx-2" asp-action="Checkout" asp-controller="Order">CheckOut</a>
    </div>
</div>

StoreApp/Pages/Complete.cshtml
@page


<div class="text-center">
    <h6 class="display-6">Thanks</h6>
    <p>Thanksa for placing order #@OrderId </p>
    <p>We'll ship yout goods soon as possible</p>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Return to Store</a>
</div>


@functions
{
    [BindProperty(SupportsGet =true)]
    public String? OrderId { get; set; }
}

StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center border my-5 rounded">
    <div class="display-6">Contact</div>
    <div class="lead">

        <i class="fa fa-phone text-primary my-3 "></i>
        <p>
            0545881270
        </p>
        <i class="fa-solid fa-address-book text-primary my-3"></i>
        <p>
            Ercüment Batanay Caddesi No 101-103 Daire 7
            İstanbul/Ataşehir Türkiye
        </p>
        <i class="fa-solid fa-envelope text-primary my-3"></i>
        <p>
           utkanylmz@hotmail.com
        </p>

    </div>

StoreApp/Pages/Demo.cshtml
@page
@model StoreApp.Pages.DemoModel
@{
}
<div class="my-5 text-center">
    <div class="display-6">Hello @Model?.FullName</div>
    <p class="text-danger">@HttpContext.Session.GetString("name")</p>
    <div class="form-group">
        <form method="post" asp-page="/demo">
            <input class="form-control" name="name" placeholder="Enter Your Name" />
            <input type="submit" class="btn btn-primary my-3" />
        </form>
    </div>
</div>